### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by teesloane** [the-heap/penny#1]
# Welcome

Hello! You made it to our **RoadMap** for **Penny**. Welcome. The Heap is happy you are here. 

For the most part, we will follow the road map step by step (stage 1, stage 2 etc), as I can only plan so much at a time — and often times in projects, things will change before you know it. 

If you've read the [README](https://github.com/the-heap/penny/blob/master/README.md) for this project then you should have a decent idea of what we're building. 

Eventually, there will be independent github issues for the majority of this checklist. If you want to contribute, please comment on an issue (or here) and you can get started!)

# THE ROAD MAP

We will have a few "milestones" for this project to help us stay organized. Issues belong to a certain "MVP" will be grouped under "milestone". You can browse / sort by filters / milestones and more on the issues page:

<img width="1002" alt="screenshot 2017-06-28 07 39 45" src="https://user-images.githubusercontent.com/12987958/27635473-268e866e-5bd5-11e7-9f03-26ddf2eff8e2.png">

The "issues" below are also known as "User Stories". A user story is user centered so that it keeps people focused on what the end user will experience while functionality is created. Each issue might involve several tasks, so many people can work together on them. Let's get into it!

## Prep Work - Admin only 

- [ ] Create a new Slack app + channel in slack for Penny
- [ ] Research libraries that might make writing a bot easier / faster

## MVP 0.1

- [ ] When I message Penny I should be able to know what its capabilities are #4 
- [ ] Penny should provide a drawing prompt when asked #5 
- [ ] Penny should announce a drawing prompt for the whole team #6 

## MVP 0.2 
- [ ] As a user I should be able to give Penny new prompts that get stored in a prompt database.
- [ ] As a team, we should be able to submit our drawings into slack (by DM'ing Penny) and at the end of the day, see a gallery of everyone's drawing.

## MVP 0.3
- [ ] As a team implementing Penny we should be able to control the bot from slack so that we can specify settings such as : The frequency of prompt dispensing.
- [ ] As a slack team we should have the option to enable a censor / filter for inappropriate prompts submitted to Penny
